apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres
          command: ['sh', '-c', 'until pg_isready -h postgres-cluster-ip-service -p 5432; do echo waiting for database; sleep 2; done;']
      containers:
        - name: server
          image: lbrady/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: pguser
                  key: PGUSER
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: pgdatabase
                  key: PGDATABASE
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
